---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
- name: run_tests
  image: python:3.9.2
  commands:
  - cd lambda/
  - pip3 install boto3
  - python -m unittest test-notifier.py
